WIP Lost in translations
OpencontentCoop/openpa_agenda pull request #31
Opened 2019-07-18 11:00 UTC by lrealdi

2019-07-18 12:07 UTC, coppo requested changes

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/agenda/parts/calendar/filters.tpl
>      <h4>{'Tematica'|i18n('agenda')}</h4>
Theme

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/agenda/parts/calendar/filters.tpl
>      <h4>{'Dove?'|i18n('agenda')}</h4>
Where

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/agenda/parts/calendar/view_pills.tpl
> +                <i class="fa fa-map fa-2x" aria-hidden="true"></i> <span class="sr-only">{'On the map'|i18n('agenda')}</span>
On map

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/agenda/parts/home_layout.tpl
> +                            <a href="{'agenda/download/'|ezurl(no)}"><b>{'Programme'|i18n('agenda')}</b></a>
Qui mi stai facendo dubitare, in effetti può essere usato anche programme

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/agenda/parts/home_layout.tpl
> +                            <small>{'Official Register of the town'|i18n('agenda')}</small>
Official Registry...

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/editorialstuff/agenda/dashboard.tpl
>                  <th>{'Modificato'|i18n('agenda/dashboard')}</th>
Modified

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/editorialstuff/agenda/dashboard.tpl
>                  <th>{'Traduzioni'|i18n('agenda/dashboard')}</th>
Translations

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/editorialstuff/agenda/dashboard.tpl
>          'Traduzioni': '{'Traduzioni'|i18n('agenda/dashboard')}',
Translations

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/editorialstuff/agenda/edit.tpl
>      'Traduzioni': '{'Traduzioni'|i18n('agenda/dashboard')}',
Translations

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/editorialstuff/programma_eventi/dashboard.tpl
>          'Traduzioni': '{'Traduzioni'|i18n('agenda/dashboard')}',
Translations

2019-07-18 12:07 UTC, coppo commented on design/agenda/templates/social_user/login_form.tpl
> +                {'In order to comment, you need to register!'|i18n('social_user/signin')}
In order to leave comment....

2019-07-30 08:07 UTC, lorello approved these changes
Perfetto!

2019-10-01 08:50 UTC, merged